### ISSUE TITLE
Possibility to add others folder/disks

### ISSUE THREAD

**Issue by Stephen988** [linuxserver/docker-rdesktop#36] opened 2021-06-27 12:32 UTC
Hello,
there is a way to explore other folder of host system? with the volume: /path/to/data:/config  I can only see the content of this specific folder, is possible mount others folders/disk, for example see content of my host home folder?

**Comment by aptalca** [comment] 2021-06-27 12:43
You can add any mount you like

**Comment by Stephen988** [comment] 2021-06-27 12:52
> You can add any mount you like

how? can you write me an example of folder path:"and here what write?"

**Comment by aptalca** [comment] 2021-06-27 13:08
It's explained in the readme as well as docker docs. Feel free to drop by our discord for further help.

Closing as this is not a bug

**Closed by aptalca** 2021-06-27 13:08 UTC

**Comment by Stephen988** [comment] 2021-06-27 13:16
> It's explained in the readme as well as docker docs. Feel free to drop by our discord for further help.
> 
> Closing as this is not a bug

chats of linuxserver discord is always closed 🔐🤷🏻‍♂️

**Comment by aptalca** [comment] 2021-06-27 13:18
You need to read the rules and the instructions
